# Generated by Django 6.0 on 2025-12-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_alter_userpreference_options_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
